### ISSUE TITLE
Support more properties and comparisons

### ISSUE THREAD

**Issue by ausi** [ausi/cq-prolyfill#1]
Examples:

```css
.child:container(font-size > 20px) {
	font-size: 0.8em;
}
.child:container(background-color lightness < 30%) {
	color: white;
}
.child:container(background-color hue > 60deg < 120deg):container(background-color lightness > 20% < 80%) {
}
.child:container(text-align = right) {
}
.child:container(opacity < 0.25) {
}
.child:container(pointer-events = none) {
}
.child:container(white-space = nowrap) {
}
.child:container(--foo = bar) {
}
.swap-visibility:container(visibility = hidden) {
	visibility: visible;
}
.swap-visibility:container(visibility != hidden) {
	visibility: hidden;
}
```
