### ISSUE TITLE
Check for max- and min-width and -height values

### ISSUE THREAD

**Issue by ausi** [ausi/cq-prolyfill#44]
In this example `.child` should not turn red:

```css
.parent {
  float: left;
  max-width: 50px;
}
.child:container(width > 100px) {
  color: red;
}
```

If a parent element between the container and the element has a `max-width` set, the containers width should be capped at that value.
