### ISSUE TITLE
Lightness Condition 

### ISSUE THREAD

**Issue by gisu** [ausi/cq-prolyfill#7]
Today i have tested your CQ Prolyfill, also the Lightness Check and i'm a little bit irritated because the Results - "its bright". With black and white Background anytime the same result. 

```css
.test {
  background-color: black; }

  .test__inner {
    color: #ccc; }

    .test:container("background-color lightness > 50%") .test__inner:before {
      content: 'its bright'; }
    .test:container("background-color lightness <= 49%") .test__inner:before {
      content: 'its dark'; }
```

I added a Test with a Single Condition with a Color (HSB Model with 30% Brightness)

```css
.test {
  background-color: #1a364d; }
  .test__inner {
    color: #ccc; }
    .test:container("background-color lightness > 50%") .test__inner:before {
      content: 'its bright'; }
```

Anytime "its bright". When i switch the Condition

```css
.test:container("background-color lightness < 50%") .test__inner:before {
      content: 'its bright'; }
```

I can set the Number from 0 to 100%, no results.

**Comment by ausi** [comment]
The container query is attached to the element you want to style. So instead of writing `.test:container("background-color lightness > 50%") .test__inner:before` like in other element query scripts, you append the query to the child itself `.test__inner:container("background-color lightness > 50%"):before`.

Your complete example should then look like:

```css
.test {
  background-color: black; }

  .test__inner {
    color: #ccc; }

    .test__inner:container("background-color lightness > 50%"):before {
      content: 'its bright'; }
    .test__inner:container("background-color lightness <= 49%"):before {
      content: 'its dark'; }
```
